### ISSUE TITLE
[Bug] Update the packages from torch 1.6.0 to be lauchable in the modern environments

### ISSUE THREAD

**Issue by kabachuha** [ChenyangLEI/All-In-One-Deflicker#1]
Right now this code depends on:

- python 3.7
- cuda 10.1
- pytorch from 3 years ago

This makes it absolutely unacceptable for the modern environments, especially if it's intended to be used as a part of a larger pipeline

**Comment by kabachuha** [comment]
```
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed
```

**Comment by xrenaa** [comment]
Hi, thanks for your report! We will have a look on this!

**Comment by hithereai** [comment]
For sucussfully running it on a 4090, you'd need to update to python 3.9 or 3.10, and a recent pytorch version as well. 

I'd try to do it myself but handling two hundreds packages is a bit hard :)

**Comment by xrenaa** [comment]
Hi all, we update the env file to python 3.10 & torch 1.12 with CUDA 11. Please check it!

**Comment by kabachuha** [comment]
Nice, thanks!

**Comment by jfischoff** [comment]
woohoo!

**Comment by jfischoff** [comment]
It works!

**Comment by gvonkreisler** [comment]
Remove simply most of the =bla.bla things in requierments.
I running the project on 4900 Win 11 vscode enviroment.
