### ISSUE TITLE
error in the end of the process

### ISSUE THREAD

**Issue by nass2020** [ChenyangLEI/All-In-One-Deflicker#13]
Thank you very much for this incredible work, unfortunately I always get this error at the end

AssertionError: the number of style frames is different from the number of content frames

--
Killed
Namespace(ckpt_filter='./pretrained_weights/neural_filter.pth', ckpt_local='./pretrained_weights/local_refinement_net.pth', fps=10, video_name='video', gpu=0)
Load ./pretrained_weights/local_refinement_net.pth
Traceback (most recent call last):
  File "/content/All-In-One-Deflicker/src/neural_filter_and_refinement.py", line 73, in <module>
    assert len(style_names) == len(content_names), "the number of style frames is different from the number of content frames"
AssertionError: the number of style frames is different from the number of content frames
-----

**Comment by xrenaa** [comment]
Hi, can you see if the number of input is equal to the number of output of the atlas? I think you should adjust the [maximum_number_of_frames](https://github.com/ChenyangLEI/All-In-One-Deflicker/blob/53bf1d65e71bde2866d287e2b5e59ac0431c5a15/src/config/config_flow_100.json#L3) to avoid the cutoff.
