### ISSUE TITLE
code for train

### ISSUE THREAD

**Issue by suzhenghang** [ChenyangLEI/All-In-One-Deflicker#14]
Nice work! Will there be open-source training code in the future?

**Comment by xrenaa** [comment]
Hi, we are preparing for releasing training code for neural filter and local deflickering network. 
However, the main problem is the training data for local deflicker network is not accessible anymore (original link is dead).

**Comment by MexWayne** [comment]
I greatly appreciate your work even regret not discovering it earlier. 
I try the flicker video with almost the light bulb flicker (not global flicker) and the results seems not work out fine and  would like to try training on my own dataset with its ground truth. 
So is it possible to release a version of the training code ?

**Comment by MexWayne** [comment]
> Hi, we are preparing for releasing training code for neural filter and local deflickering network. However, the main problem is the training data for local deflicker network is not accessible anymore (original link is dead).

I greatly appreciate your work even regret not discovering it earlier.
I try the flicker video with almost the light bulb flicker (not global flicker) and the results seems not work out fine and would like to try training on my own dataset with its ground truth.
So is it possible to release a version of the training code ?
