### ISSUE TITLE
bug,AssertionError: the number of style frames is different from the number of content frames

### ISSUE THREAD

**Issue by yifenglv46** [ChenyangLEI/All-In-One-Deflicker#15]
something wrong 

199
17.87025058686584
100% 10001/10001 [19:51<00:00,  8.39it/s]
Namespace(ckpt_filter='./pretrained_weights/neural_filter.pth', ckpt_local='./pretrained_weights/local_refinement_net.pth', fps=10, video_name='2023-05-19_20-10-50', gpu=0)
Load ./pretrained_weights/local_refinement_net.pth
Traceback (most recent call last):
  File "/content/All-In-One-Deflicker/src/neural_filter_and_refinement.py", line 73, in <module>
    assert len(style_names) == len(content_names), "the number of style frames is different from the number of content frames"
AssertionError: the number of style frames is different from the number of content frames

**Comment by yifenglv46** [comment]
The input is 203 pictures but it exits after processing to 199

**Comment by xrenaa** [comment]
Hi, please refer to "[Suggestions for Choosing the Hyperparameters](https://github.com/ChenyangLEI/All-In-One-Deflicker#suggestions-for-choosing-the-hyperparameters)":

> [Maximum number of frames](https://github.com/ChenyangLEI/All-In-One-Deflicker/blob/53bf1d65e71bde2866d287e2b5e59ac0431c5a15/src/config/config_flow_100.json#L3): We set the maximum_number_of_frames to 200. The performance for longer videos is not evaluated. It is recommended to split long videos into several shorter sequences.
