### ISSUE TITLE
Please remove os.environ["CUDA_VISIBLE_DEVICES"] = "0"

### ISSUE THREAD

**Issue by Alexdruso** [ChenyangLEI/All-In-One-Deflicker#17]
Hi guys, first of all, great scientific work!

If I may suggest an improvement to your code, though, could you factor out or fix the continuous resetting of CUDA_VISIBLE_DEVICES throughout the scripts? The problem is that in different parts of the code, you just disregard the --gpu option and just use GPU 0, which is kind of annoying for multiple GPUs setups.

A better option still would be to remove the --gpu option completely and let the user launch the script by specifying CUDA_VISIBLE_DEVICES beforehand.

If in reproducing your results I come up with a decent edit, I will open a PR. :)

**Comment by xrenaa** [comment]
Hi, thanks for your suggestion. I have removed the CUDA_VISIBLE_DEVICES.
