### ISSUE TITLE
How to run on cpu?

### ISSUE THREAD

**Issue by ReiniertB** [ChenyangLEI/All-In-One-Deflicker#20]
Hi, I try to run this on my computer, but unfortunately I do not have a GPU in it.
What argument should I use to get it to run on cpu?

Adding --cpu to the following command does not work unfortunately
python test.py --video_name data/test/Winter_Scenes_in_Holland.mp4 # for video input

**Comment by xrenaa** [comment]
Hi, I think you should comment all the operation include "to(device)" and ".cuda()". Then it should be able to run on cpu.
