### ISSUE TITLE
No module named 'src'

### ISSUE THREAD

**Issue by bySnach** [ChenyangLEI/All-In-One-Deflicker#6]
I ran into the following issue, please help me to solve, what could be the problem?:
I've verified that '**src**' folder is stored in my root folder and all **pip requirements** are installed via conda.

**(deflicker) C:\All-In-One-Deflicker>python test.py --video_name data/test/Winter_Scenes_in_Holland.mp4**

> Namespace(ckpt_filter='./pretrained_weights/neural_filter.pth', ckpt_local='./pretrained_weights/local_refinement_net.pth', video_name='data/test/Winter_Scenes_in_Holland.mp4', video_frame_folder=None, fps=10, gpu=0)
> ffmpeg -i data/test/Winter_Scenes_in_Holland.mp4 -vf fps=10 -start_number 0 ./data/test/Winter_Scenes_in_Holland/%05d.png
> ffmpeg version 2023-03-05-git-912ac82a3c-full_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
>   built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
>   configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libvpl --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
>   libavutil      58.  3.100 / 58.  3.100
>   libavcodec     60.  6.100 / 60.  6.100
>   libavformat    60.  4.100 / 60.  4.100
>   libavdevice    60.  2.100 / 60.  2.100
>   libavfilter     9.  4.100 /  9.  4.100
>   libswscale      7.  2.100 /  7.  2.100
>   libswresample   4. 11.100 /  4. 11.100
>   libpostproc    57.  2.100 / 57.  2.100
> Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'data/test/Winter_Scenes_in_Holland.mp4':
>   Metadata:
>     major_brand     : isom
>     minor_version   : 512
>     compatible_brands: isomiso2avc1mp41
>     encoder         : Lavf58.12.100
>   Duration: 00:00:08.00, start: 0.000000, bitrate: 474 kb/s
>   Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuvj420p(pc, progressive), 640x360 [SAR 1:1 DAR 16:9], 472 kb/s, 12 fps, 12 tbr, 12288 tbn (default)
>     Metadata:
>       handler_name    : VideoHandler
>       vendor_id       : [0][0][0][0]
> Stream mapping:
>   Stream #0:0 -> #0:0 (h264 (native) -> png (native))
> Press [q] to stop, [?] for help
> [swscaler @ 0000027a84806f00] deprecated pixel format used, make sure you did set range correctly
>     Last message repeated 3 times
> Output #0, image2, to './data/test/Winter_Scenes_in_Holland/%05d.png':
>   Metadata:
>     major_brand     : isom
>     minor_version   : 512
>     compatible_brands: isomiso2avc1mp41
>     encoder         : Lavf60.4.100
>   Stream #0:0(und): Video: png, rgb24(pc, gbr/unknown/unknown, progressive), 640x360 [SAR 1:1 DAR 16:9], q=2-31, 200 kb/s, 10 fps, 10 tbn (default)
>     Metadata:
>       handler_name    : VideoHandler
>       vendor_id       : [0][0][0][0]
>       encoder         : Lavc60.6.100 png
> frame=   80 fps=0.0 q=-0.0 Lsize=N/A time=00:00:07.90 bitrate=N/A speed=26.8x    ts/s speed=N/A
> video:15063kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown

> Traceback (most recent call last):
>   File "C:\All-In-One-Deflicker\src\neural_filter_and_refinement.py", line 6, in <module>
>     import src.models.network_filter as net
> ModuleNotFoundError: No module named 'src'

**Comment by bySnach** [comment]
Thanks to [@Kempeter](https://github.com/ChenyangLEI/All-In-One-Deflicker/pull/7/commits/45e83007bfed770666216fe4860f09434b6b0099)

So yea, it turns out that the problem was somehow related to '**src**' in some lines of .py files inside a folder.
I had to track the errors one by one and remove them inside the code, this helped to solve my issue.

It seems to me that the author of this repository should fix something...

**Comment by ReiniertB** [comment]
I had this problem too, but it was because I forgot to run: export PYTHONPATH=$PWD
After running that, the problem was fixed
