### ISSUE TITLE
Solving environment: failed

### ISSUE THREAD

**Issue by FurkanGozukara** [ChenyangLEI/All-In-One-Deflicker#9]
Hello. I am using anaconda and following the tutorial

Here the errors

![image](https://user-images.githubusercontent.com/19240467/227746251-70b6ecf3-884f-403d-b447-eec809ef36e9.png)

**Comment by xrenaa** [comment]
Hi, 

You can try:
```
conda create --name deflicker python=3.x
conda activate deflicker 
```
Then install the pytorch version according to your cuda version. 

And install the following package:
`matplotlib tensorboard scipy scikit-image tqdm  opencv-python imageio-ffmpeg gdown tensorboardx wandb`

If there are some missing package, just pip install them.

**Comment by ethanproia** [comment]
Having the same issue and error. Tried your solution but left with an error that there is no module named 'src'?

![noModule_src](https://user-images.githubusercontent.com/47930611/229268125-f7529295-2eee-4caa-b46e-f049a991b7e1.png)

**Comment by xrenaa** [comment]
Hi, you should export the PYTHONPATH.
